version: '3.7'

services:
  broker:
    build: ./broker
    container_name: broker
    restart: always
    volumes:
      - mosquitto_data:/mosquitto
    ports:
      - 1883:1883


volumes:
  mosquitto_data:
    driver: local